export const REAL_CATEGORIES = [
  { name: "Gummies & Candy",          icon: "🍬", color: "#FF6B6B" },
  { name: "Candy Toys (YLF)",         icon: "🍭", color: "#FF9F43" },
  { name: "Chocolate & Choco Snacks", icon: "🍫", color: "#8B4513" },
  { name: "Lollipops",                icon: "🍡", color: "#FD79A8" },
  { name: "Toys & Games",             icon: "🎮", color: "#00B894" },
  { name: "Cartoon Cakes",            icon: "🎂", color: "#A29BFE" },
  { name: "Bento Cakes",              icon: "🍰", color: "#DDA0DD" },
  { name: "Cakes",                    icon: "🎂", color: "#E17055" },
  { name: "Cake Toppers & Candles",   icon: "🕯️", color: "#FDCB6E" },
  { name: "Stationery",               icon: "✏️", color: "#0984E3" },
  { name: "Stickers & Tokens",        icon: "⭐", color: "#FFEAA7" },
  { name: "Keychains & Accessories",  icon: "🔑", color: "#B2BEC3" },
  { name: "Jewellery & Accessories",  icon: "💍", color: "#FAB1A0" },
  { name: "Hair Accessories",         icon: "🎀", color: "#FD79A8" },
  { name: "Bags & Wallets",           icon: "👜", color: "#636E72" },
  { name: "Balloons & Party",         icon: "🎈", color: "#FF7675" },
  { name: "Party Supplies",           icon: "🎆", color: "#E84393" },
  { name: "Bouquets",                 icon: "💐", color: "#00B894" },
  { name: "Drinks",                   icon: "🥤", color: "#74B9FF" },
  { name: "Packaging",                icon: "🛍️", color: "#DFE6E9" },
  { name: "Others",                   icon: "📋", color: "#B2BEC3" },
];

export type RawProduct = {
  name: string; sku: string | null; category: string;
  price: string; costPrice: string; productType: string;
  stock: number; lowStockThreshold: number; active: boolean;
  barcode: string | null; taxable: boolean;
};

export const REAL_PRODUCTS: RawProduct[] = [
  { name:"1 RM", sku:"10002", category:"Gummies & Candy", price:"1.00", costPrice:"0.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"100plus", sku:"10305", category:"Drinks", price:"2.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"2 RM", sku:"10003", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"3D Lollipop", sku:"10004", category:"Candy Toys (YLF)", price:"5.90", costPrice:"0.00", productType:"fixed", stock:19, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"3D Marshmallow duck", sku:"10006", category:"Candy Toys (YLF)", price:"6.00", costPrice:"3.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:"8888235009898", taxable:true },
  { name:"3D Marshmallow Panda", sku:"10005", category:"Candy Toys (YLF)", price:"6.00", costPrice:"6.00", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Acrylic stand", sku:"10007", category:"Keychains & Accessories", price:"9.00", costPrice:"9.00", productType:"fixed", stock:7, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Avengers", sku:"10011", category:"Toys & Games", price:"19.00", costPrice:"0.00", productType:"fixed", stock:20, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Avengers cake", sku:"10010", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Avengers PENCIL", sku:"10012", category:"Stationery", price:"3.00", costPrice:"1.50", productType:"fixed", stock:37, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"baby shark", sku:"10282", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Balloons sanrio", sku:"10361", category:"Balloons & Party", price:"3.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"bank", sku:"10283", category:"Toys & Games", price:"10.00", costPrice:"15.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"BARBIE HAPPY VAN", sku:"10013", category:"Candy Toys (YLF)", price:"6.90", costPrice:"6.00", productType:"fixed", stock:7, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Barbie Marshmellow Donuts", sku:"10019", category:"Candy Toys (YLF)", price:"3.50", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Barbie Surprise Egg", sku:"10020", category:"Candy Toys (YLF)", price:"4.90", costPrice:"2.70", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Batman Cake", sku:"10021", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bebeto sour stick", sku:"bebeto", category:"Gummies & Candy", price:"2.00", costPrice:"0.00", productType:"fixed", stock:80, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bento Cake Regular", sku:"10022", category:"Bento Cakes", price:"26.00", costPrice:"12.00", productType:"fixed", stock:4, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Best good stamp set", sku:"10023", category:"Toys & Games", price:"10.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"6982463107806", taxable:true },
  { name:"Big Bag", sku:"10025", category:"Bags & Wallets", price:"32.50", costPrice:"15.00", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big balloon", sku:"10024", category:"Balloons & Party", price:"10.00", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"big bracelet", sku:"10284", category:"Keychains & Accessories", price:"10.00", costPrice:"5.00", productType:"fixed", stock:10, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big fireworks", sku:"10329", category:"Party Supplies", price:"8.90", costPrice:"0.00", productType:"fixed", stock:3, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big Keychain", sku:"10360", category:"Keychains & Accessories", price:"11.00", costPrice:"0.00", productType:"fixed", stock:38, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"BIG Keychains", sku:"10014", category:"Keychains & Accessories", price:"9.90", costPrice:"5.00", productType:"fixed", stock:13, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big Kuromi Sticker roll", sku:"10026", category:"Stickers & Tokens", price:"3.00", costPrice:"1.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big pencil box", sku:"10312", category:"Stationery", price:"10.00", costPrice:"0.00", productType:"fixed", stock:3, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big rainbow lollipop", sku:"10028", category:"Lollipops", price:"9.90", costPrice:"6.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big Squishy", sku:"10238", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:20, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Big Wallet", sku:"10027", category:"Bags & Wallets", price:"9.00", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Birthday candle (big)", sku:"10325", category:"Cake Toppers & Candles", price:"8.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Birthday candle (small)", sku:"10326", category:"Cake Toppers & Candles", price:"6.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Blender candy", sku:"10030", category:"Candy Toys (YLF)", price:"6.50", costPrice:"4.50", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Blindbox", sku:"10031", category:"Toys & Games", price:"5.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Blindbox kuromi", sku:"10306", category:"Toys & Games", price:"5.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bouncy ball big", sku:"10356", category:"Toys & Games", price:"13.00", costPrice:"0.00", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bouncy Ball small", sku:"10032", category:"Toys & Games", price:"9.00", costPrice:"5.00", productType:"fixed", stock:4, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bouncy pals", sku:"10285", category:"Toys & Games", price:"10.00", costPrice:"0.00", productType:"fixed", stock:5, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"bouquet", sku:"10286", category:"Bouquets", price:"59.00", costPrice:"30.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bouquet", sku:"10354", category:"Bouquets", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Box", sku:"10313", category:"Packaging", price:"0.00", costPrice:"3.00", productType:"variable", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bracelet", sku:"10033", category:"Jewellery & Accessories", price:"7.00", costPrice:"9.00", productType:"fixed", stock:16, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"BRACELET CUTE", sku:"10016", category:"Keychains & Accessories", price:"5.00", costPrice:"2.00", productType:"fixed", stock:15, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bracelet pretty", sku:"10330", category:"Jewellery & Accessories", price:"10.00", costPrice:"0.00", productType:"fixed", stock:15, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Braclet china", sku:"10364", category:"Jewellery & Accessories", price:"19.00", costPrice:"0.00", productType:"fixed", stock:26, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Brookside", sku:"10346", category:"Chocolate & Choco Snacks", price:"59.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Bubble squeeze toy", sku:"10035", category:"Toys & Games", price:"9.00", costPrice:"9.00", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cable", sku:"10183", category:"Keychains & Accessories", price:"9.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cable Protector", sku:"10036", category:"Keychains & Accessories", price:"9.00", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cadbury Fruit n Nut", sku:"10323", category:"Chocolate & Choco Snacks", price:"17.90", costPrice:"6.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"9300617065029", taxable:true },
  { name:"Cake", sku:"10351", category:"Cakes", price:"65.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Camera", sku:"10018", category:"Candy Toys (YLF)", price:"11.00", costPrice:"5.10", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Candy dispenser", sku:"10038", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Candy Machine", sku:"10037", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Candy pop", sku:"10039", category:"Candy Toys (YLF)", price:"3.50", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Capsule toys", sku:"10040", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Capybara pencil sharpener", sku:"10041", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:13, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Car on play table", sku:"10334", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Caramel", sku:"10341", category:"Gummies & Candy", price:"9.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Chanel Cake", sku:"10042", category:"Cartoon Cakes", price:"99.00", costPrice:"99.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"character candle", sku:"10287", category:"Cake Toppers & Candles", price:"7.90", costPrice:"7.90", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Character Chocolate", sku:"10044", category:"Chocolate & Choco Snacks", price:"9.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Character Squishy small", sku:"10045", category:"Toys & Games", price:"5.00", costPrice:"4.50", productType:"fixed", stock:36, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"charm", sku:"10288", category:"Keychains & Accessories", price:"9.00", costPrice:"4.50", productType:"fixed", stock:48, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Charm", sku:"10348", category:"Keychains & Accessories", price:"9.00", costPrice:"0.00", productType:"fixed", stock:250, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Chocho cornet", sku:"10046", category:"Chocolate & Choco Snacks", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Chocho umbrella", sku:"10047", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Choco Umbrella 3 Pack", sku:"10048", category:"Chocolate & Choco Snacks", price:"5.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Chocolates", sku:"10049", category:"Chocolate & Choco Snacks", price:"0.09", costPrice:"0.05", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Choki choki", sku:"10308", category:"Gummies & Candy", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cinnamon roll cake", sku:"10050", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cinnamon roll pencil sharpener", sku:"10051", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:10, lowStockThreshold:0, active:true, barcode:"6977272394530", taxable:true },
  { name:"Cinnamonrol pencil set", sku:"10369", category:"Stationery", price:"12.00", costPrice:"0.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Coke", sku:"10307", category:"Drinks", price:"2.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Coloring book", sku:"10331", category:"Stationery", price:"7.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"48587389", taxable:true },
  { name:"Colourful pen", sku:"10309", category:"Stationery", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Commercial car", sku:"10054", category:"Toys & Games", price:"29.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Commercial car", sku:"10055", category:"Toys & Games", price:"29.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cornet chocho with toys", sku:"10056", category:"Chocolate & Choco Snacks", price:"5.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cosmetic mirror", sku:"10057", category:"Stationery", price:"8.00", costPrice:"7.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Crab", sku:"10058", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Crystal mud", sku:"10059", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cute animals", sku:"10060", category:"Candy Toys (YLF)", price:"8.90", costPrice:"0.00", productType:"fixed", stock:15, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cute animals lollipop", sku:"10061", category:"Candy Toys (YLF)", price:"5.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cute unicorn pen", sku:"10008", category:"Stationery", price:"0.00", costPrice:"3.00", productType:"variable", stock:12, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cute water bottle", sku:"10319", category:"Drinks", price:"25.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cutie pet", sku:"10072", category:"Toys & Games", price:"8.90", costPrice:"8.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Cutie Pet Ejection Vehicle", sku:"10062", category:"Toys & Games", price:"15.00", costPrice:"9.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Daily Candy", sku:"10063", category:"Candy Toys (YLF)", price:"3.90", costPrice:"2.20", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dinoland Cake", sku:"10064", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dinosaur", sku:"10065", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dinosaur game", sku:"10322", category:"Toys & Games", price:"10.00", costPrice:"0.00", productType:"fixed", stock:4, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dippo bon chocolate", sku:"10066", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dippo choco cornet", sku:"10067", category:"Chocolate & Choco Snacks", price:"9.00", costPrice:"9.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dippo chooky", sku:"10068", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Dippo mini cone", sku:"10069", category:"Chocolate & Choco Snacks", price:"2.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Diy", sku:"10070", category:"Stickers & Tokens", price:"10.00", costPrice:"10.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"5695201403559", taxable:true },
  { name:"Donut eraser", sku:"10071", category:"Stationery", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Doublemint gum", sku:"10289", category:"Gummies & Candy", price:"6.50", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"9555192501909", taxable:true },
  { name:"Egg big", sku:"10335", category:"Toys & Games", price:"29.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Erasers", sku:"10365", category:"Stationery", price:"5.00", costPrice:"0.00", productType:"fixed", stock:27, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Exquisitel lamp pen", sku:"10073", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:27, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fan candy", sku:"10074", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.50", productType:"fixed", stock:5, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fashion jewellery", sku:"10350", category:"Jewellery & Accessories", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fashion jewelry charms", sku:"10324", category:"Keychains & Accessories", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fast food haribo", sku:"10342", category:"Gummies & Candy", price:"2.00", costPrice:"0.00", productType:"fixed", stock:46, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fidget Candy", sku:"10076", category:"Candy Toys (YLF)", price:"4.90", costPrice:"2.80", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Fireworks", sku:"10327", category:"Party Supplies", price:"6.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Floss Candy", sku:"10077", category:"Candy Toys (YLF)", price:"4.50", costPrice:"2.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Flying punch", sku:"10078", category:"Candy Toys (YLF)", price:"8.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Frozen / Justice league Show Candy", sku:"10079", category:"Candy Toys (YLF)", price:"8.50", costPrice:"5.30", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Frozen Elsa", sku:"10080", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Funny Swing", sku:"10081", category:"Toys & Games", price:"9.00", costPrice:"5.00", productType:"fixed", stock:46, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"gas station", sku:"10290", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Gator Chomp", sku:"10082", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.20", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Giant", sku:"10083", category:"Balloons & Party", price:"14.90", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Gift Box", sku:"10336", category:"Packaging", price:"3.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Glass jar only", sku:"10085", category:"Gummies & Candy", price:"5.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Gummies & Choco MiX", sku:"10087", category:"Gummies & Candy", price:"0.09", costPrice:"0.04", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Gummy packets", sku:"10075", category:"Gummies & Candy", price:"2.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Gummy plastic", sku:"10339", category:"Gummies & Candy", price:"10.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hair Clip", sku:"10088", category:"Keychains & Accessories", price:"7.00", costPrice:"3.50", productType:"fixed", stock:9, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hair clips", sku:"10089", category:"Hair Accessories", price:"8.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hair comb", sku:"10103", category:"Hair Accessories", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Happy Anniversary", sku:"10090", category:"Cake Toppers & Candles", price:"4.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Happy Birthday", sku:"10091", category:"Party Supplies", price:"6.90", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Happy birthday banner", sku:"10093", category:"Party Supplies", price:"9.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Happy Birthday Candles", sku:"10092", category:"Cake Toppers & Candles", price:"7.90", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Haribo", sku:"10321", category:"Gummies & Candy", price:"70.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Haribo", sku:"10357", category:"Gummies & Candy", price:"3.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Haribo Gummy", sku:"10094", category:"Gummies & Candy", price:"14.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Haribo Roulatte", sku:"10095", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"hat band & long balloon", sku:"10291", category:"Balloons & Party", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Helicopter", sku:"10096", category:"Candy Toys (YLF)", price:"6.50", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello kitty", sku:"10098", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello Kitty Big Bag", sku:"10097", category:"Bags & Wallets", price:"15.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello kitty pen", sku:"10182", category:"Stationery", price:"3.50", costPrice:"2.00", productType:"fixed", stock:25, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello kitty set", sku:"10366", category:"Keychains & Accessories", price:"10.00", costPrice:"0.00", productType:"fixed", stock:3, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello kitty sharpener", sku:"10367", category:"Stationery", price:"7.00", costPrice:"0.00", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hello Pen", sku:"10333", category:"Stationery", price:"7.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"15856007", taxable:true },
  { name:"Hermes Orange Cake", sku:"10100", category:"Cartoon Cakes", price:"99.00", costPrice:"99.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Hershey's chocolate", sku:"10338", category:"Chocolate & Choco Snacks", price:"59.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Highlighter", sku:"10101", category:"Stationery", price:"5.00", costPrice:"3.50", productType:"fixed", stock:205, lowStockThreshold:0, active:true, barcode:"6958365448873", taxable:true },
  { name:"Highlighter Set", sku:"10185", category:"Stationery", price:"8.00", costPrice:"4.00", productType:"fixed", stock:9, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"ID Case Student", sku:"10102", category:"Keychains & Accessories", price:"9.00", costPrice:"4.50", productType:"fixed", stock:7, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Iron man cake", sku:"10104", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Jewelry Heart Barbie", sku:"10106", category:"Candy Toys (YLF)", price:"9.90", costPrice:"4.55", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Jungle life", sku:"10107", category:"Candy Toys (YLF)", price:"8.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"JUSTICE LEAGUE bpf BOX", sku:"10105", category:"Candy Toys (YLF)", price:"9.50", costPrice:"5.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Justice league Candy dispenser", sku:"10109", category:"Candy Toys (YLF)", price:"6.50", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Justice League mix fruit tin", sku:"10108", category:"Candy Toys (YLF)", price:"3.90", costPrice:"1.55", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kids sticker", sku:"10111", category:"Stickers & Tokens", price:"2.00", costPrice:"1.00", productType:"fixed", stock:17, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kinder happy hippo", sku:"10304", category:"Chocolate & Choco Snacks", price:"10.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kinder joy", sku:"10112", category:"Chocolate & Choco Snacks", price:"11.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kinder joy", sku:"10113", category:"Chocolate & Choco Snacks", price:"3.90", costPrice:"3.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kinder tronky", sku:"10114", category:"Chocolate & Choco Snacks", price:"11.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kinder tronky", sku:"10115", category:"Chocolate & Choco Snacks", price:"11.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kitkat", sku:"10118", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"KitKat Character", sku:"10116", category:"Chocolate & Choco Snacks", price:"3.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"KitKat mini 12pcs", sku:"10117", category:"Chocolate & Choco Snacks", price:"24.00", costPrice:"24.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"KouKou Surprise Egg", sku:"10119", category:"Candy Toys (YLF)", price:"4.90", costPrice:"2.70", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"kuromi", sku:"10292", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi and hero 2 for 25", sku:"10363", category:"Gummies & Candy", price:"25.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi Beg", sku:"10120", category:"Bags & Wallets", price:"29.00", costPrice:"16.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi cake", sku:"10123", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi cash register", sku:"10124", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"kuromi charm band", sku:"10293", category:"Keychains & Accessories", price:"9.00", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi Hello pen", sku:"10099", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:70, lowStockThreshold:0, active:true, barcode:"7974887066585", taxable:true },
  { name:"Kuromi music track", sku:"10125", category:"Toys & Games", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi pencil", sku:"10126", category:"Stationery", price:"7.00", costPrice:"0.00", productType:"fixed", stock:33, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi Piggy bank", sku:"10121", category:"Toys & Games", price:"12.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi Racing Car", sku:"10203", category:"Toys & Games", price:"9.00", costPrice:"9.00", productType:"fixed", stock:18, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi water book", sku:"10127", category:"Toys & Games", price:"10.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Kuromi Watergame", sku:"10122", category:"Toys & Games", price:"10.00", costPrice:"10.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubbu bank", sku:"10128", category:"Toys & Games", price:"49.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu", sku:"10129", category:"Toys & Games", price:"29.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu", sku:"10130", category:"Toys & Games", price:"29.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu bag", sku:"10132", category:"Bags & Wallets", price:"15.00", costPrice:"0.00", productType:"fixed", stock:5, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu blind boxes", sku:"10133", category:"Toys & Games", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu blindbox", sku:"10134", category:"Toys & Games", price:"69.00", costPrice:"69.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu cake", sku:"10311", category:"Cakes", price:"99.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu keychain", sku:"10135", category:"Keychains & Accessories", price:"5.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu music track", sku:"10136", category:"Toys & Games", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu soft candy", sku:"10137", category:"Gummies & Candy", price:"25.00", costPrice:"25.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Labubu Squishy Big", sku:"10131", category:"Toys & Games", price:"15.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Lipstick", sku:"10138", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.00", productType:"fixed", stock:18, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Little Pony & Barbie Heart Candy", sku:"10139", category:"Candy Toys (YLF)", price:"1.90", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Little Pony Sour Stripes", sku:"10140", category:"Candy Toys (YLF)", price:"6.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Lobsters", sku:"10141", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Lollipop Gun", sku:"10142", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.35", productType:"fixed", stock:214, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Long Candles 6 pcs", sku:"10143", category:"Cake Toppers & Candles", price:"6.50", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Looney Tunes Bottle", sku:"10144", category:"Candy Toys (YLF)", price:"6.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Looney Tunes Ice Cream PoP", sku:"10145", category:"Candy Toys (YLF)", price:"6.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Looney tunes Sour stick", sku:"10146", category:"Candy Toys (YLF)", price:"5.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Love ??", sku:"10148", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Love choco", sku:"10147", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"M&M chocolate", sku:"10149", category:"Chocolate & Choco Snacks", price:"14.90", costPrice:"14.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"M&M crispy", sku:"10150", category:"Gummies & Candy", price:"1.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"M&M minis", sku:"10151", category:"Chocolate & Choco Snacks", price:"3.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"M&M party box", sku:"10316", category:"Chocolate & Choco Snacks", price:"65.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Macaroon Candy", sku:"10153", category:"Candy Toys (YLF)", price:"4.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Machine car", sku:"10154", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Magic pen candy", sku:"10155", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"MAGICAL LOCK", sku:"10152", category:"Candy Toys (YLF)", price:"10.90", costPrice:"6.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Mallow Lollipop", sku:"10156", category:"Lollipops", price:"4.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Marvel Head", sku:"10157", category:"Candy Toys (YLF)", price:"8.90", costPrice:"5.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Medium", sku:"10158", category:"Balloons & Party", price:"7.90", costPrice:"2.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Meiji Strawberry Lucky Stick", sku:"10086", category:"Gummies & Candy", price:"3.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Melody", sku:"10159", category:"Keychains & Accessories", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Melody bags", sku:"10160", category:"Bags & Wallets", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Melody book", sku:"10332", category:"Stationery", price:"8.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"2123456789386", taxable:true },
  { name:"Melody Cake", sku:"10170", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Melody sticker", sku:"10161", category:"Stickers & Tokens", price:"2.50", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Merci chocolate", sku:"10162", category:"Chocolate & Choco Snacks", price:"49.00", costPrice:"49.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"mermaid cake", sku:"10294", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Milk tablet candy", sku:"10317", category:"Gummies & Candy", price:"3.90", costPrice:"0.00", productType:"fixed", stock:30, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Mini color pen", sku:"10164", category:"Stationery", price:"5.00", costPrice:"2.50", productType:"fixed", stock:95, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Mini water game", sku:"10371", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:16, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Minion Banana Spray", sku:"10166", category:"Candy Toys (YLF)", price:"6.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Minion Candy", sku:"10167", category:"Candy Toys (YLF)", price:"2.90", costPrice:"1.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"mirror", sku:"10295", category:"Stationery", price:"5.00", costPrice:"5.00", productType:"fixed", stock:68, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Mix Fruit Table Candy", sku:"10168", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Mooo Candy", sku:"10169", category:"Candy Toys (YLF)", price:"3.90", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"My little pony", sku:"10171", category:"Cartoon Cakes", price:"99.00", costPrice:"99.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Neck Strap Student", sku:"10172", category:"Keychains & Accessories", price:"9.00", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Necklace chain", sku:"10349", category:"Jewellery & Accessories", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Necklace Ramadan", sku:"10052", category:"Jewellery & Accessories", price:"20.00", costPrice:"0.00", productType:"fixed", stock:73, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Necklace set", sku:"10173", category:"Stationery", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Necklaces chain", sku:"10347", category:"Jewellery & Accessories", price:"19.00", costPrice:"0.00", productType:"fixed", stock:101, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Num Ballon Party", sku:"10174", category:"Balloons & Party", price:"3.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Number Candle", sku:"10175", category:"Cake Toppers & Candles", price:"5.00", costPrice:"2.50", productType:"fixed", stock:216, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Painting Set", sku:"10179", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Panda squeezing", sku:"10180", category:"Toys & Games", price:"9.00", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Paper Bag Kuromi", sku:"10181", category:"Packaging", price:"5.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"party happy birthday candle", sku:"10296", category:"Cake Toppers & Candles", price:"3.90", costPrice:"3.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pen sanrio bulu", sku:"10034", category:"Others", price:"0.00", costPrice:"9.00", productType:"variable", stock:16, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"pencil box", sku:"10297", category:"Stationery", price:"8.00", costPrice:"4.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"pencil box", sku:"10298", category:"Stationery", price:"10.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pencil box", sku:"10368", category:"Stationery", price:"9.00", costPrice:"0.00", productType:"fixed", stock:3, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pencil box set", sku:"10187", category:"Stationery", price:"15.00", costPrice:"19.00", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pencil Case Small", sku:"10184", category:"Stationery", price:"9.00", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pendang pen", sku:"10188", category:"Stationery", price:"9.00", costPrice:"9.00", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pepsi Can", sku:"10189", category:"Drinks", price:"2.90", costPrice:"2.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"PEZ Mario", sku:"10177", category:"Candy Toys (YLF)", price:"13.50", costPrice:"8.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Piggy", sku:"10315", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pikachu", sku:"10190", category:"Keychains & Accessories", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pinball game sanrio", sku:"10191", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"3", taxable:true },
  { name:"Plastic bag", sku:"10192", category:"Packaging", price:"0.20", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Popping Candy", sku:"10193", category:"Candy Toys (YLF)", price:"1.90", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Premium Bento cake", sku:"10194", category:"Bento Cakes", price:"29.00", costPrice:"15.00", productType:"fixed", stock:25, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Premium diary", sku:"10110", category:"Stationery", price:"10.00", costPrice:"0.00", productType:"fixed", stock:6, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pressure car duck/ hello kitty", sku:"10195", category:"Toys & Games", price:"15.00", costPrice:"5.60", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Princess Ariel", sku:"10196", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Princess Belle Cake", sku:"10197", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"PRINCESS CINDERELLA", sku:"10178", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Princess Surprise Ball", sku:"10198", category:"Candy Toys (YLF)", price:"8.90", costPrice:"5.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Pull back wheel", sku:"10318", category:"Toys & Games", price:"5.00", costPrice:"0.00", productType:"fixed", stock:21, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Puzzle caterpillar", sku:"10199", category:"Toys & Games", price:"9.00", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Racing Car", sku:"10201", category:"Candy Toys (YLF)", price:"9.90", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Racing car", sku:"10202", category:"Toys & Games", price:"9.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"RAINBOW PEN", sku:"10200", category:"Stationery", price:"5.00", costPrice:"2.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Raspberry red velvet", sku:"10029", category:"Cakes", price:"79.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Rescue Car", sku:"10205", category:"Candy Toys (YLF)", price:"6.90", costPrice:"4.30", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ring", sku:"10359", category:"Jewellery & Accessories", price:"2.00", costPrice:"0.00", productType:"fixed", stock:468, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Robot car", sku:"10355", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Rocky Caramel", sku:"10206", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Salted Caramel Chocolate", sku:"10209", category:"Cakes", price:"79.00", costPrice:"50.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio bags", sku:"10165", category:"Bags & Wallets", price:"5.00", costPrice:"5.00", productType:"fixed", stock:5, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio card", sku:"10214", category:"Toys & Games", price:"9.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"sanrio color book", sku:"10299", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio cute bags", sku:"10258", category:"Bags & Wallets", price:"19.00", costPrice:"0.00", productType:"fixed", stock:8, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio eraser", sku:"10215", category:"Stationery", price:"5.00", costPrice:"3.00", productType:"fixed", stock:43, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Hair band", sku:"10015", category:"Hair Accessories", price:"3.00", costPrice:"3.00", productType:"fixed", stock:47, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio hair clips", sku:"10241", category:"Hair Accessories", price:"3.00", costPrice:"0.00", productType:"fixed", stock:34, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio keychain", sku:"10176", category:"Keychains & Accessories", price:"15.00", costPrice:"0.00", productType:"fixed", stock:4, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio magnestism", sku:"10217", category:"Keychains & Accessories", price:"5.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:"6951458218957", taxable:true },
  { name:"Sanrio magnetic keychains", sku:"10372", category:"Keychains & Accessories", price:"0.00", costPrice:"12.90", productType:"variable", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Note book", sku:"10210", category:"Stationery", price:"9.00", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio pen", sku:"10218", category:"Stationery", price:"7.00", costPrice:"7.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Rings", sku:"10211", category:"Jewellery & Accessories", price:"5.00", costPrice:"0.00", productType:"fixed", stock:43, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Sharpeners", sku:"10186", category:"Stationery", price:"5.00", costPrice:"0.00", productType:"fixed", stock:41, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio small keychain", sku:"10216", category:"Keychains & Accessories", price:"4.00", costPrice:"4.00", productType:"fixed", stock:65, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Squishy", sku:"10212", category:"Toys & Games", price:"15.00", costPrice:"5.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio squishy", sku:"10084", category:"Toys & Games", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sanrio Stationery Set", sku:"10213", category:"Stationery", price:"11.00", costPrice:"11.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Scissors", sku:"10219", category:"Stationery", price:"5.00", costPrice:"3.00", productType:"fixed", stock:20, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Shark bite", sku:"10220", category:"Candy Toys (YLF)", price:"7.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Skittles", sku:"10221", category:"Gummies & Candy", price:"2.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Slam Dunk", sku:"10222", category:"Candy Toys (YLF)", price:"6.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Slime", sku:"10043", category:"Toys & Games", price:"9.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"slipper eraser", sku:"10301", category:"Stationery", price:"9.00", costPrice:"9.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small", sku:"10223", category:"Balloons & Party", price:"4.90", costPrice:"1.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small bag", sku:"10370", category:"Bags & Wallets", price:"5.00", costPrice:"0.00", productType:"fixed", stock:3, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small Bag Kids", sku:"10224", category:"Bags & Wallets", price:"27.50", costPrice:"14.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small balloon", sku:"10300", category:"Balloons & Party", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small Candle 10pcs", sku:"10225", category:"Cake Toppers & Candles", price:"4.50", costPrice:"1.50", productType:"fixed", stock:86, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small egg", sku:"10228", category:"Gummies & Candy", price:"1.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small Fireworks", sku:"10328", category:"Party Supplies", price:"6.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small Keychain", sku:"10226", category:"Keychains & Accessories", price:"3.90", costPrice:"2.00", productType:"fixed", stock:67, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small pritzer", sku:"10000", category:"Drinks", price:"1.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small rainbow lollipop", sku:"10229", category:"Lollipops", price:"5.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Small Wallet Character", sku:"10227", category:"Bags & Wallets", price:"7.00", costPrice:"3.50", productType:"fixed", stock:26, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Snickers & mars", sku:"10230", category:"Gummies & Candy", price:"2.00", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Snow white cake", sku:"10352", category:"Cartoon Cakes", price:"129.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Soap Character", sku:"10231", category:"Toys & Games", price:"9.00", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Soft pop candy", sku:"10232", category:"Candy Toys (YLF)", price:"5.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sour stick Looney Tunes", sku:"10233", category:"Gummies & Candy", price:"2.00", costPrice:"1.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"SOURDOUGH CARROT WALNUT", sku:"10207", category:"Cakes", price:"79.00", costPrice:"40.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sparkle", sku:"10235", category:"Gummies & Candy", price:"5.90", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"sparkling water", sku:"10001", category:"Toys & Games", price:"7.00", costPrice:"5.00", productType:"fixed", stock:22, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Spider-Man Cake", sku:"10236", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Spiderman pen", sku:"10310", category:"Stationery", price:"6.00", costPrice:"0.00", productType:"fixed", stock:15, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Spinner", sku:"10337", category:"Toys & Games", price:"4.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sports Car", sku:"10237", category:"Candy Toys (YLF)", price:"4.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Spritzer Water", sku:"10163", category:"Drinks", price:"2.90", costPrice:"0.00", productType:"fixed", stock:51, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Squishy", sku:"10239", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:15, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Squishy 2 for 25", sku:"10017", category:"Toys & Games", price:"25.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Squishy medium", sku:"10353", category:"Toys & Games", price:"9.00", costPrice:"0.00", productType:"fixed", stock:14, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Squishy toys", sku:"10240", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Squshy Ball", sku:"10314", category:"Toys & Games", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"stamper candy", sku:"10302", category:"Candy Toys (YLF)", price:"3.20", costPrice:"1.85", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sticker Book", sku:"10242", category:"Stickers & Tokens", price:"9.00", costPrice:"4.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Stickers", sku:"10243", category:"Stickers & Tokens", price:"2.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Strawberry lolipop", sku:"10244", category:"Lollipops", price:"3.00", costPrice:"1.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sugalova", sku:"10358", category:"Gummies & Candy", price:"5.00", costPrice:"0.00", productType:"fixed", stock:26, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Super hero squishy", sku:"10053", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:4, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Superman", sku:"10245", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Surprise Egg ?? BIG", sku:"10246", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Swan cake", sku:"10247", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Sweep truck", sku:"10248", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.35", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Swoguantoy", sku:"10249", category:"Toys & Games", price:"39.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"team of heroes", sku:"10303", category:"Toys & Games", price:"15.00", costPrice:"7.50", productType:"fixed", stock:2, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ten ring for RM 10", sku:"10362", category:"Jewellery & Accessories", price:"10.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Tiger Airplane", sku:"10251", category:"Toys & Games", price:"15.00", costPrice:"3.90", productType:"fixed", stock:1, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Toblerone & crunchie chocolate", sku:"10009", category:"Chocolate & Choco Snacks", price:"5.90", costPrice:"5.90", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Tofiluk", sku:"10252", category:"Gummies & Candy", price:"2.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Token x 2", sku:"10253", category:"Stickers & Tokens", price:"5.00", costPrice:"2.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Topper Birthday", sku:"10254", category:"Cake Toppers & Candles", price:"5.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Topper Hello Kitty & Mickey Mouse", sku:"10255", category:"Cake Toppers & Candles", price:"5.60", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Topper Unicorn & Rainbow", sku:"10256", category:"Cake Toppers & Candles", price:"8.80", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Transformal plane", sku:"10257", category:"Toys & Games", price:"15.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Trendy building", sku:"10259", category:"Toys & Games", price:"4.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Truck Cone Zone", sku:"10260", category:"Candy Toys (YLF)", price:"7.90", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Tsum Tsum", sku:"10261", category:"Candy Toys (YLF)", price:"2.90", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"TSUM TSUM HEART POP", sku:"10250", category:"Candy Toys (YLF)", price:"1.50", costPrice:"0.80", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Twist Pop", sku:"10262", category:"Lollipops", price:"7.90", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ultimate Chocolate", sku:"10264", category:"Cakes", price:"79.00", costPrice:"50.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ultraman Bumper Car", sku:"10265", category:"Candy Toys (YLF)", price:"10.00", costPrice:"6.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ultraman cake", sku:"10267", category:"Cartoon Cakes", price:"99.00", costPrice:"99.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Ultraman Choc Tablet", sku:"10266", category:"Candy Toys (YLF)", price:"3.90", costPrice:"2.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Under Construction Cake", sku:"10268", category:"Cartoon Cakes", price:"99.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn andle", sku:"10345", category:"Cake Toppers & Candles", price:"4.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn Bag", sku:"10270", category:"Bags & Wallets", price:"9.00", costPrice:"4.00", productType:"fixed", stock:16, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn cake", sku:"10269", category:"Cartoon Cakes", price:"129.00", costPrice:"65.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn Light", sku:"10271", category:"Candy Toys (YLF)", price:"6.90", costPrice:"4.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn Pop", sku:"10272", category:"Candy Toys (YLF)", price:"5.90", costPrice:"3.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Unicorn surprise eggs been big", sku:"10343", category:"Toys & Games", price:"15.00", costPrice:"15.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Vending machine", sku:"10273", category:"Candy Toys (YLF)", price:"9.90", costPrice:"6.65", productType:"fixed", stock:16, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Vochelle", sku:"10320", category:"Chocolate & Choco Snacks", price:"19.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Wacky Monkey Candy", sku:"10274", category:"Candy Toys (YLF)", price:"8.90", costPrice:"4.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Wafer Rolls Cup", sku:"10275", category:"Candy Toys (YLF)", price:"4.50", costPrice:"2.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Washing Machine", sku:"10276", category:"Candy Toys (YLF)", price:"8.90", costPrice:"5.00", productType:"fixed", stock:21, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Water", sku:"10277", category:"Drinks", price:"1.90", costPrice:"0.50", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Water book sticker", sku:"10279", category:"Toys & Games", price:"10.00", costPrice:"10.00", productType:"fixed", stock:8, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Water Gun Candy", sku:"10278", category:"Candy Toys (YLF)", price:"7.90", costPrice:"7.90", productType:"fixed", stock:10, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Weekend special discounts", sku:"10340", category:"Others", price:"9.90", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Wobblerz Minions", sku:"10280", category:"Candy Toys (YLF)", price:"9.00", costPrice:"4.50", productType:"fixed", stock:27, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Writing for bento cake", sku:"10281", category:"Bento Cakes", price:"2.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
  { name:"Writing for cake panda", sku:"10344", category:"Bento Cakes", price:"1.00", costPrice:"0.00", productType:"fixed", stock:0, lowStockThreshold:0, active:true, barcode:null, taxable:true },
];
